on:
  push:
    branches:
    - main
jobs:
  deploy:
    name: Deploy to production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.5
      
      - name: Install Databricks
        uses: databricks/setup-cli@main

      - name: Deploy Dataflows
        run: databricks bundle deploy 
        env:
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
          DATABRICKS_BUNDLE_ENV: prod
